### PR TITLE
Network Status pages: added pages to view Network Information

### PR DESCRIPTION
**Pull request by steglicd**
Added network status pages which supports:
* show IP (v4/v6) address and netmask
* show MAC address
* show device name
* show firewall zone name
* DNS Servers
* wifi information (like channel, SSID, rate or signal strenght)
* shared or not, is the default connection or no

ToDo:
* if connection is disabled and re-enabled again, no information are visible anymore (Bug). Currently I'm not sure if this is a bug within Networkmanager, Plinth or the network module

During refactoring I also added two enhancements to network configuration app:

1)
I added some generic network helper functions to global network helper class
to get some information from a device by it's name. This is used when editing
a connection (no ip was shown before)

2)
When selecting an existing WiFi on the "scan" page, the user will be redirected to the "WiFi add" form.
This form did not contain a WiFi capable Interface as default selection, for this reason the user get a
invalid form message when entering the form. I preselected the first wifi interface which is found on the host.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
> 1) I also added some generic network helper functions to global network helper class
> to get some information from a device by it's name. This is used when editing
> a connection (no ip was shown before)

Although, the idea of working around the crash is good, I believe this implementation is incorrect. In the edit connection interface we should be *not* be showing the current IP address of the device.  We should be showing the IP address that was set in the connection configuration.  For a DHCP configuration, this will retrieve the IP address provided by the DHCP server and automatically set (due to other modifications) it in the connections settings.  Also if there are multiple connections on the device meant for different purposes, this behavior will cause more issues.

We should instead retrieve the IP address from the connection settings (perhaps by using nmcli).  What do you think?

I am working on reviewing the rest of the patch.  I will make this change.

**Comment by steglicd** [comment]
OK, I thought that we  will bind connections to interfaces (like: 1:1). My patch includes a lot of code based in this assumption, like getting IP addresses for status page.

So currently, if you add multiple connections on top of one device, both connections will show the same information in the status page (as the information are obtained from the device).

Maybe I should change some of the patch parts.

**Comment by SunilMohanAdapa** [comment]
I think that for active connections that current patch is spot on.  For inactive connections, we should probably show the connection as inactive (with the edit button and activate button) in the status page instead of showing the status details.

**Comment by steglicd** [comment]
@SunilMohanAdapa  I agree. I will change this.

**Comment by steglicd** [comment]
@SunilMohanAdapa 
As requested I changed the pull request to not show any empty information if connection is not enabled (only a text with a hint to enable the connection).

I also split the pull requets into four commits:
* the status pages
* a pep8 fix
* fill the wi-fi add form with a network interface (to avoid a error message when entering the page)
* show the first ip of a interface which is assigned to a connection when editing the connection

As we discussed before, the last commit is not the best way but a workaround. You can pick the commits you want and drop the others.

**Comment by SunilMohanAdapa** [comment]
I have merged this after re-organizing the patch.  I meant to give you feedback and let you work on the changes but I was already feeling guilty for the huge delay in merging.  So, I made the changes myself.  Sorry about this.  Please review my changes. Major changes are as follows:

- Refactor the patch for simplicity.
- Add some more fields
- Reorganize the output fields for correctness and to improve clarity.
- Fetch the setting instead of current IP address for edit IP form.  Raised an upstream bug https://bugzilla.gnome.org/show_bug.cgi?id=756380
- Use the appropriate Wi-Fi device instead of first Wi-Fi device for add Wi-Fi connection form.

**Pull request closed without merging**
