### PR TITLE
 News Feed Reader (Tiny Tiny RSS)

### PR DESCRIPTION
**Pull request by ashokjallepalli**
Support for tt-rss is now available in plinth. Right now we are not able to configure database automatically, One way to configure is as follows:
giving this command "dpkg-reconfigure tt-rss".

Rest everything is working fine.

### CODE REVIEW

**Comment by jvalleroy** [comment]
You may be able to configure with:
```DEBIAN_FRONTEND=noninteractive dpkg-reconfigure tt-rss```
But I wonder why the database isn't configured when the package is installed.

**Comment by SunilMohanAdapa** [comment]
Hi @ashokjallepalli Did you get time to look at how to deal with answering debconf questions.  We have examples of this in other applications.

**Comment by jvalleroy** [comment]
I was able to get the database to configure automatically by adding some packages to the required list:
- postgresql
- dbconfig-pgsql
- php5-pgsql

**Comment by jvalleroy** [comment]
This has been merged with additional commits in #423.

**Pull request closed without merging**
