### PR TITLE
apps requiring login don't show up on frontpage unless logged in

### PR DESCRIPTION
**Pull request by mridulnagpal**

### CODE REVIEW

**Comment by jvalleroy** [comment]
@mridulnagpal Looks like an improvement, but we want each module to "decide" for itself whether login is required for its shortcut. So for example, in privoxy's add_shortcut(), it should have something like this:
```
frontpage.add_shortcut('privoxy', title, None, 'glyphicon-cloud-upload', description, login_required=True)
```
This way you don't need the apps_login_required set in frontpage.py.

**Comment by mridulnagpal** [comment]
@jvalleroy I did the necessary changes please review

**Comment by SunilMohanAdapa** [comment]
The patch looks good to me although I have not tested.

**Comment by mridulnagpal** [comment]
@jvalleroy @SunilMohanAdapa  Are there any other changes I need to make ?

**Comment by jvalleroy** [comment]
@mridulnagpal Looks good! I've merged this, with one minor change (change jsxc to match xmpp's login_required).

**Pull request closed without merging**
