### PR TITLE
Removed the menu issue in django 1.10

### PR DESCRIPTION
**Pull request by harry-7**
In reference to #544

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
This patch must also remove the older hack that was setting the script prefix.  Also please squash your changes into a single commit so that it is easy for review.  Explore interactive rebase in Git.

Due to urgency of the fix, I may do the above changes myself in a few hours.

**Comment by harry-7** [comment]
@SunilMohanAdapa  I made necessary changes. I ll make sure I wont keep any unnecessary commits from next time.

**Comment by SunilMohanAdapa** [comment]
I've been looking to commit this patch which looks good.  But ran into a bug with django-stronghold as soon as this patch is applied. The login and logout URLs are no longer treated as public URLs leading to infinite redirects when the session is no active.  I believe we will have to work around this. I will be raising this as another pull request which includes this patch.

**Comment by harry-7** [comment]
@SunilMohanAdapa is the removal of older hack responsible for this infinite redirect or anything else ?

**Comment by SunilMohanAdapa** [comment]
Actually, proper way of doing set_prefix=True is causing the issue.

Django stronghold is comparing request.path_info with reverse(URLs in STRONGHOLD_PUBLIC_NAMED_URLS). This will never match but due to prefix setting being hacky earlier, the prefix was never set for stronghold. Now the we are doing it correctly, the match is not happening.

**Comment by SunilMohanAdapa** [comment]
Also there are some more items that changed in Django 1.10 that we may want to fix.

**Comment by SunilMohanAdapa** [comment]
I have improved this patch and submitted this as #547 .  Closing here.

**Pull request closed without merging**
