### PR TITLE
[#846] Remove disabled apps as part of install

### PR DESCRIPTION
**Pull request by nsaikiran**

### CODE REVIEW

**Comment by JoKeyser** [comment]
Dear @nsaikiran , thank you for your two patches!
However please open a pull request (PR) for each of them. If you mix multiple commits about different issues like this, it makes the review process harder.
To keep things in order, it's a good idea if you use two different git branches for your two patches.
For example, your first commit could be in a branch `fixIssue846` and the other commit in `fixIssue759`. That way, you can also keep track of the master branch while the review of your PRs is going on. (GitHub makes it easy to open a PR if you push a branch to your own clone/checkout of Plinth.)

**Comment by nsaikiran** [comment]
Hi @JoKeyser . Thank you very much for the correction. I've created two pull requests for two patches.

**Comment by jvalleroy** [comment]
@nsaikiran #846 suggests to delete all files in the modules_enabled folder. Wouldn't this be easier? Then we can avoid maintaining a list of obsolete modules here.

**Comment by nsaikiran** [comment]
Hi @jvalleroy . As the Plinth users can include their own `app` to Plinth UI by including a file in `modules_enabled` directory with an import statement, which can live anywhere in the computer. So, I think it is not a good idea to remove *all* files in `modules_enabled` because we will be deleting files added by the user.

**Comment by jvalleroy** [comment]
@nsaikiran Ok, that makes sense. I'm ok with this general approach (still need to review the details).

**Comment by jvalleroy** [comment]
@nsaikiran I've merged this change, after rebasing to master. Thanks, and welcome to the project!

**Pull request closed without merging**
