### PR TITLE
make subcommands mandatory, fixes calls without arguments

### PR DESCRIPTION
**Pull request by JoKeyser**
For all these actions, calling without any argument lead to the same AttributeError:
```
subcommand = arguments.subcommand.replace('-', '_')
AttributeError: 'NoneType' object has no attribute 'replace'
```
Switching `subparsers.required = True` demands for the subcommands that are set up, so when now calling without arguments, the usage prompt is printed.
Something to consider: Should the script also end with an error code?

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
Merged. I believe you missed out actions/service which I covered in my change :)

**Comment by SunilMohanAdapa** [comment]
If you wish, you can further cleanup the actions/ directory by converting some of the smaller shell scripts to Python.

Another idea is to create an common action script for webserver operations so that all modules can use it like we are doing for enabling/disabling services.  This will result in removal of a lot of duplicated code in action files.  Perhaps I will create a separate task for this.

**Comment by JoKeyser** [comment]
Hi Sunil, thanks for merging. Sorry about missing actions/service, good catch.
Will think about this deeper cleanup, but it will take a while until I have sufficient time for such endevours.

**Comment by SunilMohanAdapa** [comment]
On Tuesday 11 April 2017 12:16 AM, Johannes Keyser wrote:
> Hi Sunil, thanks for merging. Sorry about missing actions/service, good
> catch.

No problem.  Make mistakes, get better :)

> Will think about this deeper cleanup, but it will take a while until I
> have sufficient time for such endevours.

While trying to make time for bigger tasks, keep your eye tiny tasks to
keep your interest and appetite fed :)

-- 
Sunil

**Pull request closed without merging**
