### PR TITLE
POST is now used to change connection state instead of GET, for CSRF …

### PR DESCRIPTION
**Pull request by stalexan**
Fixes issue https://github.com/freedombox/Plinth/issues/127
Network manager: fix CSRF when activating/deactivating network connections

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
In Django, it is possible to have the form in one page and submit it in another page.  Also, it is possible to do CSRF checks without actually having a form.  All we need to do is decorate a view with @require_POST, then make sure we make a POST request to this view.  We have used these two techniques to write simple code for CSRF elsewhere in Plinth (for example, running upgrades).

Have you considered the above and explicitly rejected the idea?

I currently find that the following items could be improved in the patch:

- Old views can be kept and decorated to require POST method.  New form ToggleConnectionForm is not really necessary.
- Javascript is being used for submitting the form.  This can be avoided too.  We have another bug that states that activating and deactivating should work without Javascript.  Current implementation is not so good for fixing that bug.
- Sleep(1) is not good.  There is no guarantee that network manager will finish its deactivating within 1 second especially when connections like 'shared' connections are involved where dnsmasq has to be stopped, and firewall rules have to be edited.  When have a fix for #189 I suspect this will less of an issue we can leave this issue be for now.

There is one suggestion in how to simplify this:

We can separate the status display from the activate/deactivate button something like this:
```
[red]    Connection 1              [Activate]     [Trash]
[green]  Connection 2              [Deactivate]   [Trash]
```
Then Activate/Deactivate options are simple form submit buttons and not drop down menus.  Javascript will not be required.  Each button can be in its own form and again Javascript is not required.  The submission URL will be different for each button's form.

Let me know what you think.

**Comment by stalexan** [comment]
The `requires_POST` decorator just marks a view function as needing to be called as a result of a POST. There still needs to be a mechanism to make the POST. A `<form>` does this, and makes the most sense in this case. You mention the upgrades module and how it uses `requires_POST`. It uses a `<form>` as well, in `templates\upgrades.html`.

I like your suggestion for not using JavaScript. I think it should be added to the comments for https://github.com/freedombox/Plinth/issues/173, though, and not be addressed here.  My personal preferece would be for JavaScript to still be used. I like the drop-down button as is. Instead, have a Plinth wide setting to disable Javascript.  Any controls that need Javascript would get rendered in a simpler way, that doesn't need Javascript. This would include rendering network connections like you suggest. It's a larger issue too, though, since JavaScript is used in other places (e.g. the dropdown menu in the upper right corner of every page.)

I agree the `sleep()` call is not ideal. This was an existing problem, though. My patch doesn't make it any worse.  It wasn't as obvious a problem because we were doing a `redirect()` that was having the same effect as the `sleep()`: giving NetworkManager a chance to finish processing the activate/deactivate request. I like your suggestion, that this should be fixed with changes to how we display status: https://github.com/freedombox/Plinth/issues/189.  

So I think this patch is good as is. There are other improvements that need to be made, but they are addressed in other issues. This patch is very targeted, and just for https://github.com/freedombox/Plinth/issues/127.

**Comment by SunilMohanAdapa** [comment]
On 09/03/2015 06:36 PM, Sean Alexandre wrote:
> The |requires_POST| decorator just marks a view function as needing to
> be called as a result of a POST. There still needs to be a mechanism to
> make the POST. A |<form>| does this, and makes the most sense in this
> case. You mention the upgrades module and how it uses |requires_POST|.
> It uses a |<form>| as well, in |templates\upgrades.html|.

An HTML <form> is indeed necessary for making a port request.  However,
the Django form is not necessary.  That would reduce the amount of
change required to fix the issue.

-- 
Sunil

**Comment by stalexan** [comment]
I've removed the Django form.

**Comment by SunilMohanAdapa** [comment]
I am merging the patch.  I hope you won't mind some of my own simplifications.

**Comment by stalexan** [comment]
Sure, that should be fine.

**Comment by SunilMohanAdapa** [comment]
I am very sorry for the delay in merge process.  I was occupied with other tasks.  I have merged the patch after rebase.  I have done the following simplifications:

* Use require_POST so that a separate form would not be necessary
* Create a separate form for each action so that the earlier /activate and /deactivate URLs could be used.
* Some trivial indentation (which was incorrect earlier to begin with)

This has significantly reduced the changes required to be made.  Please check and my changes and see if they are already.  Please reopen the issue if you disagree.

**Pull request closed without merging**
