### PR TITLE
Adds Service Discovery module

### PR DESCRIPTION
**Pull request by stalexan**
Resolves issue https://github.com/freedombox/Plinth/issues/231
"Option to disable avahi-daemon"

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
Looks great!

The only comment I have is that the name of the module could be 'avahi' instead of 'svcdiscov'.  No matter what we show in the interface, in the backend, we name the modules after the specific software that implements the functionality (there is one exception to this though due to legacy reasons). This is so that multiple competing implementations could exist (such as in case of our bittorrent clients).  Could you please rename the module to 'avahi'?

**Comment by stalexan** [comment]
> Looks great!

Thanks! And thanks for writing the app tutuorial. That was a big help.

> The only comment I have is that the name of the module could be 'avahi' instead of 'svcdiscov'. No matter what we show in the interface, in the backend, we name the modules after the specific software that implements the functionality (there is one exception to this though due to legacy reasons). This is so that multiple competing implementations could exist (such as in case of our bittorrent clients). Could you please rename the module to 'avahi'?

Sure, no problem. I've just updated the name, and pushed the changes.

**Comment by SunilMohanAdapa** [comment]
I merged the pull request after rebase and sqaushing the commits.  I also made minor changes on top.  Please check that my changes are okay.  We can revert them otherwise.

**Comment by stalexan** [comment]
Looks great, thanks.

**Pull request closed without merging**
