### PR TITLE
Setup with apt

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
Patch to run installation during initial setup using apt-get instead of PackageKit.

Also, a minor unrelated fix.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
I have tested this patch minimally for now by running --setup manually in a VM.  I am starting a image build process with foreign binaries.  I will keep updating the progress of that here.

**Comment by SunilMohanAdapa** [comment]
Update:
- I have also successfully build 'amd64' and 'beaglebone' targets without the hanging issue we have seen in the past. Build logs show no issue and that Plinth setup happened using apt-get.
- I have added a patch to this pull request to revert the changes that start dbus daemon during Plinth setup.
- I am going to build cubietruck image with the newly added patch.

**Comment by SunilMohanAdapa** [comment]
I have tested the following cases on a BeagleBone Black with fresh image built with the patch.  I have tested the functionality of various 'essential' modules which are supposed to be setup due to 'plinth --setup'. I believe everything is working as expected.  Let me if more tests are required.  My test results follow.

- After first-boot reboot, I have done the Plinth first boot wizard and it finished properly.
- Date & Time: it was already setup and works as expected. Network time server is running. Firewall shows NTP service as 'permitted (internal only)'.
- Service Discovery: it was already setup and works as expected. Service discovery is running. Firewall shows Service Discovery service as 'permitted (internal only)'.
- Power: it was already setup as expected.
- Networks: it was already setup and works as expected. Shows expected connections.
- System: it was already setup as expected.
- Names: it was already setup and works as expected. Showed the proper state of the domains (all disabled).
- Firewall: it was already setup and works as expected. Shows the current firewall state properly.
- Upgrades: it was already setup and works as expected. Automatic upgrades are enabled.
- Config: it was already setup as expected. Shows configuration form.
- Apps: it was already setup as expected.
- Help: it was already setup as expected. Shows help pages properly.
- Users: it was already setup as expected. Shows and allows creating users.
- Lets Encrypt: it was already setup as expected. Show status of certificates (empty).
- Diagnostics: it was already setup as expected. Successfully ran diagnostics.

**Comment by jvalleroy** [comment]
Merged. Thanks for the patch and thorough testing!

**Pull request merged**
