### PR TITLE
Use icon for applications button intead of text

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
The concern that people are unable to find a way to get back to
applications is a correct one.  The recent changes does fix the problem.

However, it takes a step back in the design.  The 'Applications' text is
too prominent.  I propose that we replace it with the commonly used
icon.  Featured in mobile interfaces and on Google home page, users
should have no difficulty identifing it as applications icon.

After experimenting with the placement of the icon, it seems more
asthetically pleasing to have it at the place of 'Applications' text and
not at the center etc.

### CODE REVIEW

**Comment by jvalleroy** [comment]
I also used glyphicon-th for the Name Services module. We can probably switch that icon to something more suitable. Maybe glyphicon-home?

**Comment by SunilMohanAdapa** [comment]
On 11/26/2015 09:49 PM, James Valleroy wrote:
> I also used glyphicon-th for the Name Services module. We can probably
> switch that icon to something more suitable. Maybe glyphicon-home?
> 

How about glyphicon-tag for the names module?  We should also bring in
font-awesome into Plinth at some point.  It has lot more icons.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
Added a commit that will rename the icon for 'names' module to glyphicon-tag after discussion with @jvalleroy .

**Comment by jvalleroy** [comment]
Looks good to me. @fonfon, would you like to review this change? (Since it modifies the change you made previously.)

**Comment by fonfon** [comment]
I find it confusing to have two different icons next to each other that link to the same page, I'd expect different things to happen for different icons.
How about removing the link behind the FreedomBox icon for now? (we could re-introduce the link once we have something like a dashboard, or other functionality that we'd like to integrate there)

:+1: to integrating font-awesome!

**Comment by SunilMohanAdapa** [comment]
I agree with the proposal to remove link from the logo.  Will update my pull request.

**Comment by SunilMohanAdapa** [comment]
I have rebased and remove the link from FreedomBox logo as discussed.

**Comment by jvalleroy** [comment]
I have rebased and pushed these changes to master.

**Pull request closed without merging**
