### PR TITLE
Enable ldap integration for matrix synapse

### PR DESCRIPTION
**Pull request by harry-7**
Tries to fix #1063 
@SunilMohanAdapa  I am not sure if it is possible to test these changes in a Vagrant environment.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
@harry-7, on a preliminary look, it is quite nice. We should increment the version number of the matrixsynapse package so that setup process runs again and all our current users are upgraded to have LDAP integration.

It should be possible to fully test this with VirtualBox.  See my comment on #970.

Would be nice to post what you were able to test so far.

**Comment by harry-7** [comment]
@SunilMohanAdapa  I was only able to test whether the config yaml file is being updated or not. I am not able to use the server/client.  I am getting `Can't connect to homeserver - please check your connectivity, ensure your homeserver's SSL certificate is trusted, and that a browser extension is not blocking requests.` error when I am giving https://localhost:4430 as server

**Comment by SunilMohanAdapa** [comment]
The 'invalid certificate' problem can be perhaps be dealt with in a browser.  Try using the Riot web client at riot.im (but keep the server as https://<ipaddr>:4430). First navigate to <ipaddr>:4430 and add certificate exception, then use Riot client.

**Comment by harry-7** [comment]
@SunilMohanAdapa  I already have an exception for https://localhost:4430 in my browser (firefox) and trying to use the webclient at riot.im but still I am getting the same error.

**Comment by SunilMohanAdapa** [comment]
Browser have special provisions to prevent websites from accessing `localhost` URL. Try IP address or your machine instead. Parts of my earlier comment go eaten up by Github.

**Comment by harry-7** [comment]
@SunilMohanAdapa . I have successfully tested these changes and all of them are working now. How ever in our ldap schema we don't have the email and Full name information so I currently set those fields to `uid` as well.  Do you think it is okay to keep it that way?

**Comment by SunilMohanAdapa** [comment]
Nice patch on a important feature.  I merged it, with changes, however.  I incremented the plinth module version number so that all existing users will get LDAP integration and some changes related to that.  I also turned off public registration for new installs.

**Comment by harry-7** [comment]
@SunilMohanAdapa  .. Great :-D . Thanks :)

**Pull request closed without merging**
