### PR TITLE
[WIP] disks: Warning about insufficient space on root partition 

### PR DESCRIPTION
**Pull request by JoKeyser**
This PR addresses issue #985, showing messages to warn about insufficient space on the root partition. I consider this a workaround until a proper, general notification system is implemented, see #867.

In the current implementation, warnings are shown if the remaining used space is either <10%  or <1GiB free space (severe, in red), and if either <25% or 2GiB (less severe, in yellow). The percentage thresholds match the ones used for coloring on the Disks page. The warnings are shown on the main index page, on the System Configuration, and on Disks itself.

One simple way to test it is by generating a big data file, to trigger the warning, e.g. `fallocate -l 1G nullbytes`.

Here two screenshots:
spacewarning1

And from the main page (looks a bit odd, as messages don't take up all space...):
spacewarning2

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
* We should not be showing notifications to all the visitors of the FreedomBox (image those who have come to read someone's blog).  Even regular users perhaps should not be shown the notification, since only admin is in a position to take action on the warning.
* I am somewhat worried that we are running the `df` and `lsblk` commands on every request to the front page including search engine crawls. (The view function now takes about 10ms instead of 0.1ms on a good VM and number might be worse on a SD card based devices.)

Perhaps we could restrict the checking as well as showing warning to just admin users.

**Comment by JoKeyser** [comment]
@SunilMohanAdapa thanks for checking this. I agree with your points, and I'd like to know how you checked loading times, to be able to check them in the future as well.
I'll add the admin check (pointers how to do that very welcome), so this should be considered WIP until then. And now I also realise I should have rebased the commits and signed-off.

**Comment by JoKeyser** [comment]
Hi @SunilMohanAdapa , please take another look.

**Comment by SunilMohanAdapa** [comment]
Thanks for the update.  To measure the time, I just wrote a quick and dirty time.time() around the code in the index() view like this:
```python
start_time = time.time()
...
print('Time taken: ', time.time() - start_time)
```

I am currently review the patch.

**Comment by SunilMohanAdapa** [comment]
Merged this with a patch with following minor changes.  Please review them.

disks: Minor changes for styling and performance

- Enable cached results when checking if the user is an admin. Cached results
  are only invalid when a user newly get admin permission or when an existing
  user loose admin permission. Here the consequence of showing wrong results is
  minor.

- Use all small case for variable names.

- When we use a utility method from Plinth, we can trust it to give expected
  values. Otherwise, we should fix the method to be more robust.

- Don't recommend the user to go to disks configuration page as there is not
  much there to do to free up space. The action might be removing apps, deleting
  downloaded content (downloaded via torrents) etc.

- df is unlikely to return '-1' for size of disk.

- Avoid using -1 as error value.

Signed-off-by: Sunil Mohan Adapa <sunil@medhas.org>

**Comment by JoKeyser** [comment]
Hi @SunilMohanAdapa , thanks a lot for the extensive review and improvements, I'm learning a lot from it again, although it's just a small patch.
I agree that the linking to the Disks page wasn't the best idea, especially right now when you can maybe only expand the partition. Instead, there probably should be a short, general entry in the manual how to increase disk space.

**Comment by SunilMohanAdapa** [comment]
> Instead, there probably should be a short, general entry in the manual how to increase disk space.

That would be nice, indeed.

**Pull request closed without merging**
