### PR TITLE
Fix for overwrite and shaarli icon

### PR DESCRIPTION
**Pull request by MarkoMackic**
Referencing issues #724 #721

### CODE REVIEW

**Comment by jvalleroy** [comment]
@MarkoMackic I also found that setup.py install has a ```--force``` option:
http://stackoverflow.com/questions/19133831/python-how-to-force-overwriting-of-files-when-using-setup-py-install-distutil
Would this work to install over existing folders?

**Comment by MarkoMackic** [comment]
I don't think it would since you're using `shutil.copytree` and in [docs](https://docs.python.org/2/library/shutil.html#shutil.copytree) it says the destination directory must not exist.

**Comment by MarkoMackic** [comment]
In these commits I referenced #720 too

**Comment by jvalleroy** [comment]
@MarkoMackic We should also add license information for the logo to LICENSES.

**Comment by MarkoMackic** [comment]
Done, I think this is ok now.

**Comment by jvalleroy** [comment]
@MarkoMackic Thanks, I have merged this (after rebase) with just a few changes for code style.

**Pull request closed without merging**
