### PR TITLE
Added Basic Access Control for Radicale

### PR DESCRIPTION
**Pull request by harry-7**
In reference to Issue #488 Added Basic Access Control Option

### CODE REVIEW

**Comment by harry-7** [comment]
@jvalleroy if we create a views.py and forms.py file and migrate these to respective files, Will it be better ?

**Comment by jvalleroy** [comment]
@harry-7 Yes, that would be better I think.

Also note that, at least for setting the value, we should use the action script: https://github.com/freedombox/Plinth/blob/master/actions/radicale

To do this, you can add a new subcommand like "configure" with a parameter for the new setting value. Then use something like this:
```
actions.superuser_run('radicale', ['configure', '--rights', new_value])
```
The reason is that, although Plinth runs as root user currently, we want to change it to run as non-root. Then only actions.superuser_run will have sudo permissions.

**Comment by harry-7** [comment]
@jvalleroy I have made necessary changes. Have a look once

**Comment by jvalleroy** [comment]
@harry-7 I have rebased and merged this change. I also made some minor edits:
- Fix code style (like breaking up long lines, etc).
- Keep description and util functions at module level.
- Add license notice to forms file.
- Internationalize and make choice descriptions more informative.

Please check that these changes look ok.

**Comment by harry-7** [comment]
They look good thanks for the changes. I ll try to include format_lazy :P from next time

**Comment by harry-7** [comment]
@jvalleroy Also check the state of the branch master when I tried to checkout it showed me it is in a detached head state.

**Pull request closed without merging**
