### PR TITLE
Radicale CalDAV/CardDAV module

### PR DESCRIPTION
**Pull request by jvalleroy**
- Uses SSL with snakeoil certificate.
- Uses LDAP for user authentication, all valid users are authorized.
- Authenticated users have access to all calendars / addressbooks.
- Note when using DAVdroid, you first have to create an addressbook with another client program (I used Evolution).

Further improvements to consider:
- Use certificate from letsencrypt.
- Add LDAP group for caldav/carddav users.
- Add options to restrict access to "owner write" or "owner only".

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
The patch looks good except for a major item.

We should not expose 5232 port to users and instead setup Radicale (and any other web service behind Apache) for the following reasons:

- We will have to separately manage certificate configuration for Radicale.
- Radicale will need to have SNI support to work for multiple domains with SSL.
- With Apache, we can redirect /.well-known/caldav and /.well-known/caldav nicely so that clients discover the radicale path without having to remember the port or path.

So, radicale should run without SSL.  Radicale port should not be exposed to outside.  Apache configuration to perform reverse proxying should be setup.

**Comment by agropper** [comment]
I'm not caught up on how FreedomBox uses LDAP, but it seems to me that this kind of app would benefit a lot from incorporating and OpenID Connect client. That work is going on in HIE of One right now. I'm not a fan of proprietary social login, but a broadly accessible standard like OIDC, would be good for the usability and adoption of FreedomBox.

**Comment by petterreinholdtsen** [comment]
As far as I know, CalDAV and CardDAV can not use OpenID, as it require an interactive web browser, while the calendar clients run in the background.

**Comment by agropper** [comment]
I hope I'm taking this discussion into a rathole and please feel free to say-so if I am. 

CalDAV and WebDAV Access Control (rfc3744) are based on acls. I don't understand acls but I do see that most commercial Web services are protected by OAuth and derived protocols like OpenID Connect and, soon, UMA. I sense that the "linked data" folks are not playing nicely with the OAuth folks and I'm not really sure why. 

My applications are either in the health records or IoT domains. Health records are being exclusively standardized around OAuth and OpenID Connect. I have not heard mention of acls in healthcare in years. IoT is a bit more fluid, I have not seen much standardization in terms of either authentication or authorization in IoT.

Authentication and Authorization are absolutely critical to FreedomBox and calendars are an example from this perspective. I want my calendar app to be compatible with people's Google and Apple calendars, maybe even Outlook :-) If anyone has a reference that explains the difference between acl and OAuth as access control frameworks, I would appreciate it and might be able to help.

**Comment by SunilMohanAdapa** [comment]
On 02/01/2016 03:56 AM, Adrian Gropper wrote:
> I hope I'm taking this discussion into a rathole and please feel free to
> say-so if I am.
> 
> CalDAV and WebDAV Access Control (rfc3744) are based on acls. I don't
> understand acls but I do see that most commercial Web services are
> protected by OAuth and derived protocols like OpenID Connect and, soon,
> UMA. I sense that the "linked data" folks are not playing nicely with
> the OAuth folks and I'm not really sure why.
> 
> My applications are either in the health records or IoT domains. Health
> records are being exclusively standardized around OAuth and OpenID
> Connect. I have not heard mention of acls in healthcare in years. IoT is
> a bit more fluid, I have not seen much standardization in terms of
> either authentication or authorization in IoT.
> 
> Authentication and Authorization are absolutely critical to FreedomBox
> and calendars are an example from this perspective. I want my calendar
> app to be compatible with people's Google and Apple calendars, maybe
> even Outlook :-) If anyone has a reference that explains the difference
> between acl and OAuth as access control frameworks, I would appreciate
> it and might be able to help.
> 

There is a flow in OAuth in which does not require browser interaction
and user provides the application with username and password.  This is
done when the application is trusted.  Access token is returned by the
server and this can be sent to the server while requesting a resource on
a CalDAV server using HTTPS.

The usual OAuth flow requires an interactive browser.  Web applications
and even some mobile/desktop applications use this (despite the need for
browser interaction; there are solutions).  After the initial browser
interaction and 'access token' has been issued, it can be reused for
further interactions.  When the access token gets expired, a fresh one
may automatically be obtained using a 'refresh token'.  This flow has
the advantage that user can grant limited access to a third party for a
resource without revealing a password.  In case of CalDAV the use case
could be to allow a third party site or application limited readonly
access for a calender that is not publicly available.

The use case here is, however, not very strong (unlike Adrian's HIE of
One effort).  Both CalDAV servers and clients will have to be modified
to provide support for OAuth.

In general, we need to provide OAuth and OpenID Connect and related
standards into FreedomBox.  However, in my opinion, our efforts are best
spent on focusing on existing and upcoming applications that are built
around OAuth before getting into ones like CalDAV.

-- 
Sunil

**Comment by jvalleroy** [comment]
I have pushed a commit with these changes:
- Served behind apache at /radicale.
- Redirect /.well-known URIs.
- Use remote_user authentication.
- Set access control to "owner_only".

I think these changes are correct, but I'm seeing a few issues with different clients:
- Icedove / Evolution: Doesn't try the well-known URIs automatically. I had to specify to use them.
- DAVdroid: Unable to create calendar or addressbook. Works after these are created by another client.

**Comment by petterreinholdtsen** [comment]
[James Valleroy]
> I have pushed a commit with these changes:
> - Served behind apache at /radicale.
> - Redirect /.well-known URIs.
> - Use remote_user authentication.
> - Set access control to "owner_only".
>
> I think these changes are correct, but I'm seeing a few issues with
> different clients:

You might want to test the service using caldav-tester,
<URL: https://bugs.debian.org/742999 >.  The git content mentioned in
the WNPP request is uploaded to Debian and waiting in NEW now.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SunilMohanAdapa** [comment]
Overall structure looks okay.  Due to string changes involved and string freeze currently in effect, will merge this after tagging 0.8.

**Comment by petterreinholdtsen** [comment]
[Sunil Mohan Adapa]
> Overall structure looks okay.  Due to string changes involved and
> string freeze currently in effect, will merge this after tagging 0.8.

Oh, that was sad.  I was really looking forward to testing this in v0.8.
I hope it will be available soon in Debian for testing. :)

--
Happy hacking
Petter Reinholdtsen

**Comment by SunilMohanAdapa** [comment]
I merged this branch after rebase and some modifications:
- Adapted to new setup mechanism.
- Fixed issue with non-existant firewall service.
- Made the server listen only on internal addresses for added security.
- Minor fixes elsewhere.

Please check my changes.  I have tested with Lightning and things went smooth (haven't tried well-known).  I don't think DAVDroid has the ability to create calenders at all.  This is not Radicale specific.

**Comment by SunilMohanAdapa** [comment]
Also, I am somewhat worried about the fact that anyone logging into terminal can access all calenders by faking remote user proxy headers.  This is not a big issue because currently only administrators can login to the system.  Same level of security might be required for other services we have behind Apache.  We should never allow non-root users to login for now.  Perhaps a mechanism such as WSGI module or secure socket communication is a better to put services behind Apache and delegate authentication to Apache.

**Pull request closed without merging**
