### PR TITLE
Frontpage configure button added

### PR DESCRIPTION
**Pull request by mridulnagpal**
I added the configure button for configurable apps on the frontpage which link to the main apps page.

### CODE REVIEW

**Comment by jvalleroy** [comment]
@mridulnagpal I haven't reviewed this fully yet, but for apps that don't require login, we should still hide the Configure button unless the user is logged in.

**Comment by mridulnagpal** [comment]
@jvalleroy Fixed it.

**Comment by jvalleroy** [comment]
@mridulnagpal I would like to suggest a few changes. Here is a screenshot of the current view:
plinth-frontpage-configure
1. Instead of showing the configure buttons all the time, only show it for the currently selected shortcut. Also move the button down into the details box at the bottom of the page.
2. Since web apps don't have the detailed view on the frontpage, I would just not show the configure button for those. (It seems like too much clutter on the page. But maybe someone will have an idea on a good way to display it.)
3. I noticed the shortcut buttons are now bold, but I don't think that improves the overall appearance. I would suggest leaving it as original.

**Comment by mridulnagpal** [comment]
@jvalleroy I started again and have linked the button into the shortcut description. The PR regarding this is #655

**Pull request closed without merging**
