### PR TITLE
App View

### PR DESCRIPTION
**Pull request by mridulnagpal**
@jvalleroy Made the icons big enough and text is below it

### CODE REVIEW

**Comment by jvalleroy** [comment]
I hope we can get some more opinions on whether this look is preferred over the current front page. We can also discuss it in the next progress call.

For reference, here's a screenshot of the front page with this change applied.
plinth-frontpage-large-icons

**Comment by mray** [comment]
These are problems I see:
* there is little connection to the way those apps appear - compared to where they get installed.
* the problem of arbitrary icons applies to this overview as well; meaning of icons gets lost. i think using the respective project icons makes more sense
* the placement of the welcome text is unlucky (seperate to the icons in a strange way - why not centerd?)

Those issues aren't necessarily ones that I'd change right now.
I think the real problem is the underlying lack of strategy in UX, we probably need to revamp mayn parts of the UI all over the places at some time.

**Comment by jvalleroy** [comment]
There were also some suggestions made in the progress call:
https://wiki.debian.org/FreedomBox/ProgressCalls/2016-11-27
I added those to the task list in #594.

I think the main concern for this specific change (making the icons larger) is that it emphasizes the icons over the text, but the icons aren't sufficient to distinguish between applications. So we should fix that issue before merging this change.

**Comment by mridulnagpal** [comment]
@jvalleroy @mray Made some changes please have a look

**Comment by mray** [comment]
Could you upload a screenshot please?

**Comment by mridulnagpal** [comment]
@mray Here you go
screenshot from 2016-12-01 17 50 32

**Comment by mray** [comment]
Thank you! That is better already Looking at the screenshot my impression is that:

* There icons can be smaller, but still be big
* there needs to be some more padding on the top (between the first icon row and the navbar, maybe double it?)
* the text paragraph on the bottom needs to be narrower (about 1/3  or 1/2 of its current width)

I expect this to be a temporary view as mentioned in #666 so don't spend too much effort in it anyway.

**Comment by mridulnagpal** [comment]
Ohh Cool can I do anything for the new view?

**Comment by mray** [comment]
As I suggested I'm interested in requirements that should be met, as well as in aspects about other systems that work great and could be copied.

**Comment by jvalleroy** [comment]
I've merged these changes, but for now I set the icon size to 300% as a compromise (so we don't minimize the importance of the text too much).

**Pull request closed without merging**
