### PR TITLE
Consolidation of client info + UI improvements

### PR DESCRIPTION
**Pull request by JosephKiranBabu**
This is to remove duplication between the client api exposed in #1066 and the information required for UI changes made in #1014.

There is also some additional work building upon #1066.

### CODE REVIEW

**Comment by JosephKiranBabu** [comment]
I believe this pull request is now ready for review. 
In addition to DRYing up the client information in #1066 and #1014, this pull request adds a graphical representation of the clients in the Plinth UI.

_**Default state on both Setup View and Service View**_
screenshot from 2017-11-20 20-54-28

_**Expanded state**_
screenshot from 2017-11-20 20-55-14

_**Multiple clients of one type**_
screenshot from 2017-11-20 20-56-13

The choice of clients is not the best nor comprehensive. Client information can be refined in future pull requests. This pull request establishes the framework so that client information can be easily updated in the future.
The focus of this pull request is to build up framework that serves two purposes:
1. serve a JSON response over the /api/1/services.json url for the Android app, and
2. display a list of clients for each app on the Plinth web UI

**Comment by JosephKiranBabu** [comment]
**Known issue**
Toggling the "Client Apps" button currently doesn't work with Javascript disabled, although this pull request itself doesn't introduce any new Javascript code.

**Comment by JosephKiranBabu** [comment]
Adding this to Milestone 0.18 since it's a blocker for the Android app release. We can release the very first version of the FreedomBox Android app once this api is available on the FreedomBox server.

**Comment by mray** [comment]
This is how I see the UI could be improved:

***Default state***
image

***Expanded state***
image

***Multiple clients of one type***
image

maybe you feel like incorporating part of it.

**Comment by SunilMohanAdapa** [comment]
Thoughts on @mray 's suggested changes:
* \+ Cleaner due to less horizontal lines
* \+ Clear grid layout with all cell having same sizes.  More pleasing.
* \+ Consistent sizing of icons/buttons.
* \+ More pleasing spacing.
* \+ Icons for apps look good. But acquiring icons with right format and license for so many clients could become a challenge.
* \- Original design has green color on Web client for emphasis only since it can be launched immediately and user may be looking for it. Using green on too many things looses emphasis, like bolding too much text.
* \- Web has to be emphasized over other types of clients because it is launched many times while others are installed once and later not used. Also because this page is served in a browser. Ordering and UI may be different in mobile clients.
* \+ Swapping the axises looks good.
* \- Swapping the axises has problems:
  * First priority of the user will be to choose a platform rather than choose a client.
  * We like to recommend a client for each platform and order the clients based on order of recommendation.
  * We foresee more clients (such as RPM, DEB etc.) to appear in desktop clients list and this can be more space efficient when presented horizontally.

**Comment by JosephKiranBabu** [comment]
@mray Thanks for the design suggestions. 
This is what it looks like after incorporating some of your suggestions. 

**On Desktop browser**

screenshot from 2017-11-29 17-12-47

**On a Nexus 5 phone**

screen shot 2017-11-29 at 17 19 17

**Comment by mray** [comment]
> - Original design has green color on Web client for emphasis only since it can be launched immediately and user may be looking for it. Using green on too many things looses emphasis, like bolding too much text.

An alternative would be to stick to blue as a link color (like other elements). Black should not be the color of any link, though.

> - Web has to be emphasized over other types of clients because it is launched many times while others are installed once and later not used. Also because this page is served in a browser. Ordering and UI may be different in mobile clients.

Can you elaborate on that extra importance of mobile applications? It might be best to not press them into an equal structure and then highlight them afterwards. I think web applications are delicate as it is unclear whether they run on FreedomBox or on third party Servers. Also I feel uncomfortable to make too much of an invitation to make people use other servers, as that opposes our goals to self host. To me they feel strange in that list.

> - Swapping the axises has problems:
    First priority of the user will be to choose a platform rather than choose a client.

What do you mean by "platform" (desktop vs. mobile – google vs. apple)? I don't see any downside compared to the initial UI. 

> We foresee more clients (such as RPM, DEB etc.) to appear in desktop clients list and this can be more space efficient when presented horizontally.

So the simple categorization "Desktop" does not apply anymore and would be "Desktop/Distribuition". Finding a solution that is usable and space efficient would require to rethink the whole client section.
We already have more than two axis:  project |  platform | vendor + (Distribution?). Maybe rethinking this section from scratch is a good idea. But then again it might be better to wait for a general overhaul of the UI ...

**Comment by mray** [comment]
I really don't support the nested client sorting as it makes the list very hard to read – especially in multiple client situations. Platform sorting in columns vs. rows does not make that much of an impact. Also long lists are not that much of a problem, any device can scroll up/down easily.

**Comment by jvalleroy** [comment]
I've merged these changes. I opened #1160 to track remaining issues, please add to that.

**Pull request closed without merging**
