### PR TITLE
Enable apt-transport-tor

### PR DESCRIPTION
**Pull request by jvalleroy**
- Adds checkbox to Tor configuration form to enable/disable apt-transport-tor.
- Enabled automatically after Tor setup.

### CODE REVIEW

**Comment by jvalleroy** [comment]
I pushed one more commit, so it doesn't try to enable tor for non-http(s) apt source types (like cdrom).

**Comment by SunilMohanAdapa** [comment]
The Augeas based configuration change looks beautiful. :)

I have incorporated your change to my review changes. However, there are other things that need fixing in this patch:

- Does not consider files in sources.list.d/ directory.
- Should report as not enabled even if a single URL is not through Tor.
- Should load Augeas minimally for speed.
- Disabling Tor fails all installations later.
- Augeas lens has a bug that it does not understand the [arch=amd64] kind of directive in the sources file.

I am halfway making changes for the above.  Will commit your patch soon along with my fixes.

**Comment by SunilMohanAdapa** [comment]
I have rebased you changes and merged into master with my own fixes mentioned above.

* For `[options]` problem I created a work around, however, we need to actually fix the Augeas lens. Cdrom URLs with space in them are also not handled by this lens properly.
* For Deb822 format, I have made sure that the option is not enabled when such files are detected.  Apt 1.1 (in experimental) supports sources.list.d/*.sources files which are of this format.  We need implement a new lens for this based on debctrl lens.

**Comment by SunilMohanAdapa** [comment]
Please check that my changes are okay.

**Pull request closed without merging**
