### PR TITLE
Full internatlonalization

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
This patch does almost full internatlonalization.  Having double check everything, I have tested using a fake locale.  The locale is included in this pull request. Rename the locale to a real locale and set the browser to send that locale as first language priority.  All the Plinth text will show up in upper case.

We still need a way to compile and install .mo files during installation process.  We need to deal with i18n for the string returned from actions.  We could give way for user to change the language preference in profile.  Finally we need to update the developer documentation.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
This fixes #278.

**Comment by jvalleroy** [comment]
I'm having a few issues trying to check this:
- I don't see any translated strings, except for built-in Django forms. (Tested with Iceweasel and Chrome.)
- The {{ cfg.box_name }} string isn't shown, for any locale.

Any ideas?

Also, the nb locale file should be moved & updated.

**Comment by jvalleroy** [comment]
Ah maybe I missed it, is fake the only supported locale currently?

**Comment by SunilMohanAdapa** [comment]
On 11/14/2015 06:10 AM, James Valleroy wrote:
> I'm having a few issues trying to check this:
> 
>   * I don't see any translated strings, except for built-in Django
>     forms. (Tested with Iceweasel and Chrome.)

- You will need to compile the strings using the command 'cd plinth;
django-admin compilemessages -a'

- Run it as './run ... ' with local plinth.config and not one in /etc/ .
 We are not yet installing the .mo files into proper location.

>   * The {{ cfg.box_name }} string isn't shown, for any locale.
> 
> Any ideas?

I think I made a mistake here.  When doing blocktrans we are supposed to
explicitly mention what variables to use.  Let me fix this.  You can
proceed with review however as I will do this as additional commits.

> 
> Also, the nb locale file should be moved & updated.

I missed this one due to last minute merge.

On 11/14/2015 06:13 AM, James Valleroy wrote:
> Ah maybe I missed it, is fake the only supported locale currently?
>

All other locales should work too.  However, notthing much is translated
in any locale other than French.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
I have made more changes:

- Move missing nb locale file too
- Fix issues with template expressions causes box_name to not show up properly.

**Comment by jvalleroy** [comment]
Looks good, I've merged this.

**Pull request merged**
