### PR TITLE
Migrate to Django 1.10

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
This patch is based on @harry-7 's fix for #544 which is #546 .

I went through the complete Django 1.10 release notes for deprecations and removals.  I fixed all that noticed.  Also, since testing also has Django 1.10, this patch proposes depending on it as minimum version.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
@harry-7 as continuation of our discussion, see the changes that were required for `stronghold` application to fix the recursive redirections on login page.  Consider doing an additional review of this patch to help @jvalleroy .

@jvalleroy , since we need to fix a current live issue, we have two options:
- Make a release after merging this leading to Plinth 0.10.
- Branch 0.9 and apply first four patches in this series (other two can be ignored).  Then make a release from there.

**Comment by SunilMohanAdapa** [comment]
@harry-7 , I have created a [bug report](https://code.djangoproject.com/ticket/27050) for the Django documentation issue we have found.

**Comment by harry-7** [comment]
@SunilMohanAdapa  I checked the files and ran through the code that is changed. The patch looks fine for me. I wonder we should update our INSTALL file mentioning that we need django 1.10 now. what do you say ?

**Comment by jvalleroy** [comment]
Merged. I also updated the Django version requirement in INSTALL and requirements.txt.

Thanks @harry-7 and @SunilMohanAdapa for the quick fixes!

**Pull request closed without merging**
