### PR TITLE
Implement many more diagnostic tests

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
- Move all the remaining diagnostics from freedombox-setup

- Add basic diagnostics for many more modules.

This pull request is dependent on 'diagnostic-framework' and 'tor-setup' pull requests. Please merge those first for simplicity.

### CODE REVIEW

**Comment by jvalleroy** [comment]
I've committed these changes along with some minor fixes. Please check that my changes are correct.

**Comment by SunilMohanAdapa** [comment]
I have checked your changes.  They all look good, sorry about the silly mistakes.

In Tor diagnostics we are setting the return results as 'error: missing command'.  I meant the return value to be strictly one of 'error', 'passed' or 'failed' so the meaning it could be understood to prepare statistics etc.  It is also used to set the proper CSS class on the displayed result.  If we intent to show the error message to the user, we need to perhaps add another field in the returned results and also internationalize the string.  I suggest we change it to just 'error'.

**Comment by jvalleroy** [comment]
@SunilMohanAdapa Ok, we can change it to 'error'. I think we can also remove this line, because it causes 'error' to be displayed twice:
https://github.com/freedombox/Plinth/blob/master/plinth/modules/diagnostics/templates/diagnostics_results.html#L40

**Comment by SunilMohanAdapa** [comment]
On 08/29/2015 06:53 PM, James Valleroy wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa> Ok, we can change
> it to 'error'. I think we can also remove this line, because it causes
> 'error' to be displayed twice:
> https://github.com/freedombox/Plinth/blob/master/plinth/modules/diagnostics/templates/diagnostics_results.html#L40

Yes, that line should be removed.

-- 
Sunil

**Comment by jvalleroy** [comment]
Ok, I've made that change as discussed and pushed to master.

**Comment by SunilMohanAdapa** [comment]
On 08/29/2015 07:09 PM, James Valleroy wrote:
> Ok, I've made that change as discussed and pushed to master.

Looks good, thank you.

-- 
Sunil

**Pull request closed without merging**
