### PR TITLE
LDAP login and group management

### PR DESCRIPTION
**Pull request by jvalleroy**
This pull request is on top of the ikiwiki LDAP one, so those changes are included here as well.

I also sent a patch to freedombox-setup (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792233) which configures PAM to allow LDAP users to login.

Changes:
1. Add posixAccount class for LDAP users. However only users in the admin group will be allowed to log in to the system through SSH.
2. Don't create POSIX users outside of LDAP.
3. The groups for a user can be selected when creating or updating the user. Currently there are 2 selectable groups: admin and wiki.
4. Users in the admin group are also added to a posixGroup which gives them sudo privileges.

I am planning to work on another pull request for remaining XMPP cleanups related to LDAP. Also there is a Django LDAP auth module in Debian, but it is lacking a python3 package (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782917).

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
I have been reviewing this patch and close finishing it.  Two things come to my mind:

- We should not be passing passwords via command line and should use stdin for it. This is more secure.  (This make the log-only-command-in-some-cases unnecessary).

- We should perhaps be using `ldapscripts` package for user and group management.

**Comment by jvalleroy** [comment]
@SunilMohanAdapa,
Thanks for the review and suggestions. I will try to add those changes onto this pull request. One question below about using stdin.

(Also @NickDaly)
Plinth's actions.py lists the following limitation:
```
6. (limitation) Providing the process with input is not possible.

   Don't expect to give the process additional input after it's started.  Any
   interaction with the spawned process must be carried out through some other
   method (maybe the process opens a socket, or something).
```
Is this something that could be changed? My plan is to provide an optional input string when calling actions.run, setup a PIPE for stdin, and use the input string as a param to proc.communicate(). Does this sound ok?

**Comment by SunilMohanAdapa** [comment]
On 07/18/2015 07:01 PM, James Valleroy wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa>,
> Thanks for the review and suggestions. I will try to add those changes
> onto this pull request. One question below about using stdin.

I started working on ldapscripts migration.  I considering merging these
changes with minor modifications and then we can split work on the
review comments one each.  What do you think?

> 
> (Also @NickDaly <https://github.com/NickDaly>)
> Plinth's actions.py lists the following limitation:
> 
> |6. (limitation) Providing the process with input is not possible.
> 
>    Don't expect to give the process additional input after it's started.  Any
>    interaction with the spawned process must be carried out through some other
>    method (maybe the process opens a socket, or something).
> |
> 
> Is this something that could be changed? My plan is to provide an
> optional input string when calling actions.run, setup a PIPE for stdin,
> and use the input string as a param to proc.communicate(). Does this
> sound ok?

Yes, keeping current and likely needs in mind, I don't think we will
have to be communicating with the process constantly.  So, a simple
input string parameter sounds good.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
Current set of changes have been merged.  We will be creating separate pull requests for the two items we are going to work on.

**Pull request closed without merging**
