### PR TITLE
Add Shadowsocks client

### PR DESCRIPTION
**Pull request by jvalleroy**
This add a Shadowsocks module to install and configure shadowsocks-libev. Currently, only client configuration is supported. It will also run a socks5 proxy for devices on the local network. When device use this proxy, their data will be encrypted and sent through the configured Shadowsocks server.

The current use case is when the FreedomBox's upstream connection is filtering/censoring certain sites or protocols. FreedomBox can connect to a Shadowsocks server that isn't filtered, and proxy traffic from local devices.

I think this is sufficient for the initial implementation, but here are some things we can add in the future:
- Also handle outgoing connections from FreedomBox itself.
- Transparent proxying with ss-redir.
- Configure and run Shadowsocks server.

### CODE REVIEW

**Comment by JosephKiranBabu** [comment]
@jvalleroy Suppose a user already has privoxy installed, then all traffic in the FreedomBox passes through the privoxy proxy. Thus, people are using FreedomBox as an ad filter in their network, by placing it between the internet cable and the router. (I didn't do it myself, so not sure if it works like that.)
Now, if shadowsocks is also installed on the same FreedomBox, can we somehow make the traffic both censorship-resistant and ad-free? Maybe by passing it through shadowsocks first and then passing it through privoxy?

**Comment by jvalleroy** [comment]
@JosephKiranBabu Privoxy has a forward-socks5 option that can be used for this:
https://www.privoxy.org/user-manual/config.html#FORWARD
We can add an option to the Privoxy page to do this when Shadowsocks is enabled.

But note that FreedomBox doesn't have an option to send all data through Privoxy (yet). It has to be configured as proxy on the client device.

**Comment by JosephKiranBabu** [comment]
I'm confused on whether `shadowsocks-libev` is a client or a server or both.

I tried to give a 3rd party server's details in the Service View. The server supported only `aes-256-cfb`, which is not one of the listed options. Shouldn't we let the encryption method be a text field instead of a drop-down?

**Comment by jvalleroy** [comment]
@JosephKiranBabu shadowsocks-libev includes several services:
- shadowsocks-libev: Shadowsocks server.
- shadowsocks-libev-local: Shadowsocks client / SOCKS5 proxy server
- shadowsocks-libev-redir: Shadowsocks client / transparent proxy
- shadowsocks-libev-tunnel: port forwarding tool

I agree we can add more encryption methods, but some of the supported methods are insecure. On the other hand, a text field will remove the need to update every time a new method is added.

**Comment by SunilMohanAdapa** [comment]
@jvalleroy Thank you for another awesome contribution. I have merged this pull request but with some changes. Please review my changes.

- Description to reflect how to use the service including port number.
- Added ciphers, but not by making it a text field (yet). Many free services online where still not using recommended ciphers.
- Use restart instead of reload (service file has no reload mechanism).
- Create configuration file that can't be read by other users on the system (due to password being stored).
- Minor change to actions/service. Unrelated.

Further discussion can be on new issues.

**Pull request closed without merging**
