### PR TITLE
run as plinth user

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
I haven't experienced any errors during running this script,
this pull request is in reference to issue #38

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
The change to `ExecStart` is incorrect. On a system which has Plinth installed from Debian package, plinth binary will be available from /usr/bin/plinth.

To gain confidence on the patch, could you please explain the tests you have performed running Plinth as non-root user?

**Comment by nikhilrayaprolu** [comment]
I have checked most of the app installations and enabling and disabling the apps but when I have run the sudo python3 setup.py test ,I got these two errors.
```
======================================================================
ERROR: test_gpt_partition_free_space (plinth.modules.disks.tests.test_disks.TestActions)
Test that GPT partitions can be expanded.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/proj/Plinth/plinth/modules/disks/tests/test_disks.py", line 162, in test_gpt_partition_free_space
    with Disk(self, 256, disk_info, [(5, 'btrfs')]):
  File "/root/proj/Plinth/plinth/modules/disks/tests/test_disks.py", line 109, in __enter__
    self._create_disk_file()
  File "/root/proj/Plinth/plinth/modules/disks/tests/test_disks.py", line 58, in _create_disk_file
    subprocess.run(command.split(), stderr=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dd', 'if=/dev/zero', 'of=/root/proj/Plinth/plinth/modules/disks/tests/temp_disk.img', 'bs=1M', 'count=256']' returned non-zero exit status 1

======================================================================
ERROR: test_simple_case (plinth.modules.disks.tests.test_disks.TestActions)
Test a simple with no complications
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/proj/Plinth/plinth/modules/disks/tests/test_disks.py", line 129, in test_simple_case
    with Disk(self, 256, disk_info, [(3, 'btrfs')]):
  File "/root/proj/Plinth/plinth/modules/disks/tests/test_disks.py", line 109, in __enter__
    self._create_disk_file()
  File "/root/proj/Plinth/plinth/modules/disks/tests/test_disks.py", line 58, in _create_disk_file
    subprocess.run(command.split(), stderr=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dd', 'if=/dev/zero', 'of=/root/proj/Plinth/plinth/modules/disks/tests/temp_disk.img', 'bs=1M', 'count=256']' returned non-zero exit status 1


```

**Comment by SunilMohanAdapa** [comment]
On 07/28/2016 11:02 PM, Nikhil Rayaprolu wrote:
> I have checked most of the app installations and enabling and disabling
> the apps but when I have run the sudo python3 setup.py test ,I got these
> two errors.
> 

The errors don't look like a consequence of the changes.  You simply
might have run of disk space when creating 256MB test data file.

For the thorough testing, kindly test the following:

- Run one test for each of the methods in action_utils.py
- Run one test for each of the subcommand in the actions directory
- Run tests by creating/modifying/activating/deactivating/deleting
network connections.  These are likely to fail and we have to work on
writing a polkit policy file.
- Visit help pages.

Thank you,

-- 
Sunil

**Comment by nikhilrayaprolu** [comment]
Checked by installing some apps and enabling and disabling them.to compensate unit tests available by plinth I manually set the user as plinth using os.setuid() and run the `python3 setup.py test` . I can't guarantee that everything is fine.If some vulnerable point in the code where this may fail is  shown ,I will test whether this is working fine there.Is there any other better way to test plinth in this case(when we start plinth using plinth.service)

**Comment by jvalleroy** [comment]
Would it make sense to have ```ExecStart=/usr/local/bin/plinth``` in upstream, and patch it to /usr/bin/plinth in the Debian package?

**Comment by nikhilrayaprolu** [comment]
@SunilMohanAdapa @jvalleroy can I know where the subcommands in action directory are called ,so that I could test upon those.

**Comment by SunilMohanAdapa** [comment]
On 07/31/2016 08:38 PM, Nikhil Rayaprolu wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa> @jvalleroy
> <https://github.com/jvalleroy> can I know where the subcommands in
> action directory are called ,so that I could test upon those.

You will find the subcommands in action/*:parse_arguments().  They are
also available by running 'action/* --help'.  For example,
action/firewall --help.  These are called from their corresponding
modules such as plinth/modules/firewall/*.py

-- 
Sunil

**Comment by nikhilrayaprolu** [comment]
1)=>Run one test for each of the methods in action_utils.py
https://github.com/freedombox/Plinth/blob/master/plinth/action_utils.py#L220
this function should be run as super user but no sudo permissions are given in the final call run by this function.(Need to check complete `WebserverChange(object)`  class  in action_utils.py. Can I know where the  `WebserverChange(object)`  class is used ?
2)=>Run one test for each of the subcommand in the actions directory
there is no problem with subcommands in actions directory function as all functions in actions directory are called as a superuser(as per documentation)

**Comment by nikhilrayaprolu** [comment]
=>Run tests by creating/modifying/activating/deactivating/deleting network connections. These are likely to fail and we have to work on writing a polkit policy file.
running these tests found that some functions(while adding,editing and deleting) need to be run as superuser ,which are causing the error due to no user privileges.

**Comment by SunilMohanAdapa** [comment]
On 07/31/2016 11:02 PM, Nikhil Rayaprolu wrote:
> =>Run tests by creating/modifying/activating/deactivating/deleting
> network connections. These are likely to fail and we have to work on
> writing a polkit policy file.
> running these tests found that some functions(while adding,editing and
> deleting) need to be run as superuser ,which are causing the error due
> to no user privileges.

Instead of running these functions as superuser, we can create a polkit
file that lets Plinth, even without superuser privileges, perform
network management operations.  This is possible because Plinth, in
order to perform network management functions, communicates with Network
Manager daemon using the D-Bus protocol.  Policy management for this
communication is enforced using polkit.

-- 
Sunil

**Comment by nikhilrayaprolu** [comment]
can I have some references on how to write a polkit file.

**Comment by SunilMohanAdapa** [comment]
@nikhilrayaprolu , I am currently reading https://www.freedesktop.org/software/polkit/docs/latest/ to understand polkit and writing polkit files.

**Comment by SunilMohanAdapa** [comment]
I have also started to test this.  I found that dyanmicdns module is no longer working after this patch.  Raised a pull request to fix that: #556 .

**Comment by SunilMohanAdapa** [comment]
@nikhilrayaprolu , looks like we need to create a javascript based policy file for polkit in /usr/share/polkit-1/rules.d/ . We have examples in the polkit documentation and also in the file /usr/share/polkit-1/rules.d/60-network-manager.rules .  Let me know if you want me to take care of this.

**Comment by SunilMohanAdapa** [comment]
Another issue: in software upgrades, getting whether package manager is busy and showing the upgrade log don't work.

**Comment by SunilMohanAdapa** [comment]
Preliminary test report:

* Basic

- Packages: update
- Packages: install

- Service: is-enabled
- Service: is-running
- Service: enable/disable
- Service: start/stop
- Service: reload?

- Log to syslog
- Log to access.log
- Log to status.log

* Help

- Help: index
- Help: manual
- Help: status logs
- Apps: Index

* System

- System: Index

- ? Certificates:

- Configure: get/set hostname
- Configure: get/set domainname
- Configure: get/set language

- ? Diagnostics: 
- Diagnostics: diagnose port listening

- Date: ntp server count diagnostic

- Disks: get free space and list of partitions
- Disks: is expandable
- (failed) Disks: expand partition/file system (due to busy warning)

- Dynamic DNS: getting/setting configuration (running actions as root)
- Dynamic DNS: getting status page (running actions as root)

- Firewall: get running status
- Firewall: get service status
- Firewall: Add/remove services

- ? Monkeysphere

- Name Services: list services and domains

- Power: restart
- Power: shutdown

- Pagekite: start/stop
- Pagekite: enable/disable
- Pagekite: restart
- Pagekite: is disabled
- Pagekite: get/set frontend
- Pagekite: get/set kite
- Pagekite: get/add/remove services

- Security: add/remove access.conf restriction

- Service Discovery: enable/disable

- Snapshots: setup fstab
- Snapshots: setup root configuration
- Snapshots: create snapshot
- Snapshots: delete snapshot
- ? Snapshots: restore snapshot

- Software upgrades: setup, enable auto upgrades
- Software upgrades: get/enable/disable auto upgrades
- Software upgrades: manual upgrade
- (failed) - Software upgrades: package manager busy
- (failed) - Software upgrades: get log

- Users: create user
- Users: diagnose ldap entry
- (failed) Users: rename user (with an unrelated bug)
- Users: add/remove users from group
- Users: get/set SSH keys
- Users: set user password
- Users: delete user

**Comment by SunilMohanAdapa** [comment]
I found that reading transmission configuration as non-root is a problematic.  Raised a pull request for it. https://github.com/freedombox/Plinth/pull/557

**Comment by SunilMohanAdapa** [comment]
Canceling monkeysphere's publish operation is failing due to insufficient privileges.

**Comment by SunilMohanAdapa** [comment]
Mostly done with full testing. Here is the updated report. 

[non-root.org.txt](https://github.com/freedombox/Plinth/files/425495/non-root.org.txt)

**Comment by SunilMohanAdapa** [comment]
After merging #573 , I believe we can merge this patch.  The remaining items in the test list look harmless and unlikely to fail because of the patch.

**Comment by SunilMohanAdapa** [comment]
#584 has been merged allowing network manager code to run as non-root.  I believe this patch can be merged now.  There is one task that needs to be done in Debian package to change the ownership of `plinth.sqlite3` file to `plinth:plinth` from `root:root`.

**Comment by SunilMohanAdapa** [comment]
I have merged this.  Will create a bug in Plinth's Debian package to change the ownership of /var/lib/plinth/plinth.sqlite3.

**Pull request closed without merging**
