### PR TITLE
first_boot: de-bloat first welcome screen; fixes A,B of #830

### PR DESCRIPTION
**Pull request by JoKeyser**
This addresses points A,B in issue #830, please see there for more context.

### CODE REVIEW

**Comment by jvalleroy** [comment]
@JoKeyser There was a suggestion in #830 to change the button text to "Install Apps", would you like to include this change?

**Comment by JoKeyser** [comment]
@jvalleroy sorry for the delay; yes I'm gonna change this and add to the conversation in a few hours, still at work :).

**Comment by jvalleroy** [comment]
@JoKeyser Thanks, I've merged this. I made one additional change, to replace the "Go to Networks" button with a link from the existing text:
firstboot_complete_new

**Comment by JoKeyser** [comment]
Thanks, that improves it further!

**Comment by JoKeyser** [comment]
@jvalleroy , note you merged all the individual commits, including "silly ones" where I forgot to change the exclamation mark. I think it would have been better to squash them into one commit (or ask me to do a rebase before merging).

**Comment by jvalleroy** [comment]
@JoKeyser Ok, I'll keep that in mind.

**Pull request closed without merging**
