### PR TITLE
Collapsible Accordion implementation for network module's connection_show.html file

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
worked on the issue
https://github.com/freedombox/Plinth/issues/322
where I have added the bootstrap's collapsible accordion property here. # #322 

I have tested it on my pc on both not activated and an activated network and has worked fine.
here I am pasting a preview image of the output collapsible http://imgur.com/LHaOq4j

### CODE REVIEW

**Comment by jvalleroy** [comment]
I haven't fully reviewed this yet, but I noticed a couple things that might need some work:
- The 1st commit looks a bit strange. You shouldn't need a merge commit in a pull request.
- The 2nd commit has author info for "root" (probably was committed as root user). You should amend this commit with --reset-author.
- A lot of the changes are just changing indentation. It's ok to correct indentation, but the changes don't seem to correct it.

**Comment by nikhilrayaprolu** [comment]
I have made a new pull request by changing all the commit mistakes over here.so it would be better if we close this pull request.

**Comment by nikhilrayaprolu** [comment]
secondly what is the convention to indent django templates in freedombox that is followed .Is there any automatic way of indenting django templates in any editor in the we are indenting the templates here.

**Comment by harry-7** [comment]
It seems this pull request is no longer required. @nikhilrayaprolu If that is the case please close this one

**Comment by jvalleroy** [comment]
@nikhilrayaprolu Regarding template indentation, I try to follow the existing templates which have 2 spaces indent for each opening HTML tag, and also for each opening template tag.

At least with my current configuration, emacs doesn't recognize the template tags, so I indent those manually.

**Pull request closed without merging**
