### PR TITLE
add Dockerfile for development

### PR DESCRIPTION
**Pull request by nikolas**
This adds a Dockerfile so you don't have to install all of Plinth's
required debian packages on your host machine in order to run it.

Let me know if you have any suggestions.. I just thought this could
be a good alternative to VirtualBox / KVM. It also provides a place
to document what's actually needed to get Plinth running.

I've added some instructions on how to run this to the INSTALL file.

    docker build .
    docker run -p 127.0.0.1:443:443 [image-hash]

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
We really need something like this for new contributors to easily adopt to Plinth development.  However:

- Does this work with the necessity that other servers have to be up and running for Plinth to do well?  For example does firewalld, slapd, networkd etc.  run and work as expected?  My limited understanding of Docker hints me that Docker is well suited for running a daemon whereas we need a whole system to running properly to develop and test.

- Vagrant on the other hand can be used to setup a full virtual machine where freedombox-setup can be installed (to setup LDAP etc.) and where all the required daemons are properly started before running Plinth.  Vagrant will also give us the same easy of setup and development.  Did you get a chance to look at Vagrant?  Did you rule it out for some reason?

- Vagrant also gives us a shared working directory with the main machine.  This will allows to edit source code in the main directory and see the changes reflected in the container.

- I assume that the pgi changes are from previous submission.  I will soon review and commit it, sorry about the delay on that.

**Comment by SunilMohanAdapa** [comment]
@nikolas I have been reading more about Vagarant.  Any comments on my thoughts?

**Comment by nikolas** [comment]
It seems like there is a lot of overlap between what Docker and Vagrant can do. I'm not completely clear about the difference, but Vagrant seems like a fine alternative in this case. I didn't rule out Vagrant, I just don't have any experience with it, while I have a little experience with Docker.

> Does this work with the necessity that other servers have to be up and running for Plinth to do well? For example does firewalld, slapd, networkd etc. run and work as expected?

Not as configured on this branch. To do that, I think we could set something up with [docker-compose](https://docs.docker.com/compose/).

**Comment by nikolas** [comment]
Closing this after some discussion with Sunil. Sounds like Vagrant is better suited to development specifically for Plinth. So a PR adding a Vagrantfile would be useful.

**Comment by fgro** [comment]
Vagrant vs Docker explained/discussed: 

https://stackoverflow.com/questions/16647069/should-i-use-vagrant-or-docker-for-creating-an-isolated-environment

After reading this I also believe that Vagrant is better suited for development purposes.

**Pull request closed without merging**
