### PR TITLE
Service refactoring

### LINKED ISSUE #415: Reuse code for enabling/disabling services
@fonfon floated the idea of reusing the code for enabling/disabling a service from action.  In each module there is a lot of boiler plate code enabling and disabling services. The discussion went like this:
- We agreed that we should reuse the code.  This can be done by writing an function to enable/disable a service and using it in all modules.
- However, this will not play nice when Plinth starts running as non-root user.
- Then we can create a common action script for enabling and disabling all services.
- We loose a bit on security here because currently the set of services manageable for Plinth is restricted to our apps.  But with this approach there is no restriction.

Here is a possible solution: we will define a variable in each `<module>/__init__.py` as `services_managed: ['service1', 'service2']` etc.  Then we will write a common action script that takes three arguments `<module_name> <service_name> <enable/disable>`.  Then the action script will:
- Obtain the module path from /etc/plinth/modules-enabled/<module_name>
- Import the module and obtain list of services.
- Check that services asked for is part of that list.
- Go ahead and perform operations on that service.

@fonfon What do you think? Are you interested in taking it up?

### PR DESCRIPTION
**Pull request by fonfon**
The changes consist of three building blocks:
- `actions.service` offers basic services actions like start/stop/restart (in order to use it, a service has to be in the 'managed_services' variable of any plinth module)
- `plinth.service.Service`: Use additional methods for restarting etc. - it operates on the `service_id` that it's given, using `actions.service`. All offered methods can be overridden/customized.
- `plinth.views.ServiceView`: Provides a default form, view and template to show and enable/disable a service.

These changes aim at removing repetitive code, making more coherent use of Django functionality, and to move functionality to where it belongs.

The next step is to combine `service` with `managed_services`. I propose having one dictionary instead of these two variables, like: `services = {'avahi': None}`, where `None` is replaced by the actual service in `init()`.
With that (and small additional changes) we have all information and functionality required for the dashboard (that's a quick overview page to show installed apps/services, and to start/stop them). 
`actions.service list` is not yet used but may be used for the dashboard, except if we collect and cache the information about which services are running during plinth startup, and only use the new service-interface to start/stop services.

This closes #415 .

### CODE REVIEW

**Comment by jvalleroy** [comment]
Looks good overall, but there are duplicate description paragraphs on the Dynamic DNS page.

Also there seems to be a mix between having descriptions in module init files or in templates. Is one way preferred over the other?

**Comment by fonfon** [comment]
Thanks for the hint, I updated the dyndns page.

Having the description in  `__init__.py` has two advantages:
1. we can use it in more than one place, perhaps in the dashboard (it's only an advantage if we really do this)
2. simple modules can use  `ServiceView` (which uses the `service.html` template), and don't have to create an extra template for each page.

The disadvantage is that the preferred django way is having such content in the template. 

I don't have a strong preference here, people should do what they prefer. With the dashboard we might have to add a description for each module -- if there is enough space there to display it, so I wouldn't worry about it now.

**Comment by jvalleroy** [comment]
Any idea about the Travis CI failure?

**Comment by fonfon** [comment]
The reason travis CI failed was a circular import, that's fixed now.
Strangely it didn't cause any problems on my VM and all tests were passing when run locally.

**Comment by jvalleroy** [comment]
I've merged this after rebasing and signing the commits.

**Pull request closed without merging**
