### PR TITLE
Updated: Unit tests #1

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
I have added a couple of more tests and fixed minor styling issues.  This is a commit on top of rebased #86.

### CODE REVIEW

**Comment by BobGirard** [comment]
I fully approve of all of @SunilMohanAdapa's improvements to my pull request #86.

**Comment by fonfon** [comment]
I pointed out to @BobGirard via e-mail a while ago that the `rename_official_config_file` (https://github.com/SunilMohanAdapa/Plinth/commit/e69b5002472d3af892eefb20e574ea5cbcefef27#diff-b75de6f5f50b45f17d77b7ff21828074L142) is potentially harmful when renaming back fails. (I don't know whether Bob worked on that already, perhaps you could coordinate to not do the same work twice.)

**Comment by BobGirard** [comment]
This was entirely my misunderstanding, or simply unfamiliarity with the protocol.  Yes, I do want to refactor the test to prevent the production copy of plinth.config from being altered in any way.  But when @SunilMohanAdapa turned pull request #86 into this pull request, I thought that I'd avoid complicating things even further, and would wait until this pull request was merged into the master, and then merge it from there into my local repo to do the refactoring.  If we want my refactoring to be included in pull request #98, then I'll go ahead with it, although it may take me a day or so.

**Comment by fonfon** [comment]
There's no fixed protocol for that. 
So there's nothing wrong with basing further work/refactoring on this pull request in your branch.
I'd prefer to leave `rename_official_config_file` out of production and refactor it before merging, instead of merging it and fixing it with another pull request.

**Comment by BobGirard** [comment]
OK, I'll see what I can do here to provide an alternative to the method in question.  If I can't put together something better soon, I'll just yank this logic out for now, and then think about a more definitive approach later.

**Comment by BobGirard** [comment]
Improvements made in this pull request have been included in an update which was made to pull request #86 to address the above review issue, and therefore this pull request can be closed without further action.

**Comment by SunilMohanAdapa** [comment]
Closing as these changes are included in #86.

**Pull request closed without merging**
