### PR TITLE
Implement middleware for admin views

### PR DESCRIPTION
**Pull request by lispyclouds**
This is in reference to the bug #426 

This adds the middleware needed to intercept requests to admin areas and treats all non public views as admin unless decorated as "non admin"

- Add AdminMiddleware to deny non admin users
- Add decorator to mark views as "non admin"

### CODE REVIEW

**Comment by lispyclouds** [comment]
This is still a work in progress. Not ready for a merge yet.

**Comment by lispyclouds** [comment]
This can now be merged.

**Comment by lispyclouds** [comment]
Feature Hopefully Complete. 😄

**Comment by SunilMohanAdapa** [comment]
Congratulations on your first contribution to the FreedomBox project :) .  I have merged these patches with some fixes and updates. Please see my changes as review comments.

**Pull request closed without merging**
