### PR TITLE
fix file permission for dynamic DNS user credentials

### PR DESCRIPTION
**Pull request by steglicd**
The file which contains the credentials should not be readable for "others"

### CODE REVIEW

**Comment by steglicd** [comment]
see https://github.com/freedombox/Plinth/issues/555

**Comment by SunilMohanAdapa** [comment]
When saving the configuration from Plinth, the configuration file permissions are still incorrect.  During update, configuration file is being created again.  Here the permission is getting reverted to rw-r--r-- values.

Also it is better to set `600` as permission explicitly rather than doing `o-r`.

**Comment by steglicd** [comment]
@SunilMohanAdapa good catch, I missed this. I also updated the permission to 600 as you proposed.

**Comment by SunilMohanAdapa** [comment]
After reading more about these creating file security, I believe that using umask may be a better approach.  There is a brief period between the data creation and setting permissions.  An adversary can take advantage of this and retrieve the data in that period.  Using umask will prevent this problem. Please consider using this approach.

**Comment by SunilMohanAdapa** [comment]
By setting umask we can globally, we can make sure all files created will be only be accessible by root (just to be safe).

**Comment by steglicd** [comment]
@SunilMohanAdapa by saying to setting umask globally you mean that plinth should umask when invoking the action script?

**Comment by SunilMohanAdapa** [comment]
Sorry for being unclear.  I mean just for dynamicdns but for all write operations its performs.  Something like before a call to writecfg() and before call to update().  Whatever those to operations do, the umask will be applicable.

**Comment by steglicd** [comment]
@SunilMohanAdapa I have updated the PR. I was thinking about something like storing current umask and change it back afterwards. But having all files with this permission may be the safest solution. 

Also the umask is only valid in the context of the script call, so changing at the beginning and leave it as it is should work.

**Comment by SunilMohanAdapa** [comment]
Merged. Thanks for the patch.

**Pull request closed without merging**
