### PR TITLE
Django 1.9

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
Django 1.9 is unstable now and we are not ready for it.  Plinth fails to run with this version.  This pull request contains various fixes to address this.

### CODE REVIEW

**Comment by jvalleroy** [comment]
Trying to start plinth with these changes, I get:
```django.db.utils.OperationalError: table "plinth_kvstore" already exists```

Do I need to remove /var/lib/plinth to continue? Will it still be possible to upgrade plinth 0.6 to 0.7?

**Comment by SunilMohanAdapa** [comment]
On 12/05/2015 05:47 AM, James Valleroy wrote:
> Trying to start plinth with these changes, I get:
> |django.db.utils.OperationalError: table "plinth_kvstore" already exists|
> 
> Do I need to remove /var/lib/plinth to continue? Will it still be
> possible to upgrade plinth 0.6 to 0.7?
> 

This is a problem.  I have not tested this case.  I will check how to
handle this scenario.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
The additional commit just pushed, should take care of the migrating from 0.6.

**Comment by jvalleroy** [comment]
Looks good now. I have rebased these changes and pushed to master.

**Pull request closed without merging**
