### PR TITLE
snapshots: Button to delete all snapshots

### LINKED ISSUE #1144: Snapper: Button to delete all the snapshots
`snapper delete` command with range argument like `1-10` can be used for deleting the snapshots.
The current list of snapshots can be fetched using `snapper list`.

### PR DESCRIPTION
**Pull request by JosephKiranBabu**
- closes #1144

Signed-off-by: Joseph Nuthalapati <njoseph@thoughtworks.com>

### CODE REVIEW

**Comment by JosephKiranBabu** [comment]
I tagged the issue as beginner, but snapshots filling up my VM was getting too annoying, so I implemented it myself.

**Comment by JosephKiranBabu** [comment]
This is what the UI looks like, for reference.

screenshot from 2017-11-22 20-35-35

**Comment by jvalleroy** [comment]
One issue I found: when there are no snapshots, it still allows you to click "Delete All", leading to this error:
```
[2017-11-29 04:11:08,041] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/snapshot', 'delete-all'], , Traceback (most recent call last):
  File "/usr/share/plinth/actions/snapshot", line 181, in <module>
    main()
  File "/usr/share/plinth/actions/snapshot", line 177, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/snapshot", line 157, in subcommand_delete_all
    to_delete = '-'.join([rng[0], rng[-1]])
IndexError: list index out of range
```

**Comment by jvalleroy** [comment]
Another issue, when there is just 1 snapshot:
```
[2017-11-29 04:12:42,025] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/snapshot', 'delete-all'], , Identical snapshots.
Traceback (most recent call last):
  File "/usr/share/plinth/actions/snapshot", line 181, in <module>
    main()
  File "/usr/share/plinth/actions/snapshot", line 177, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/snapshot", line 159, in subcommand_delete_all
    subprocess.run(command, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snapper', 'delete', '1-1']' returned non-zero exit status 1.
```

**Comment by jvalleroy** [comment]
On the confirmation form, should "Delete Snapshots" button be red instead of blue?

**Comment by JosephKiranBabu** [comment]
@jvalleroy Thanks for the thorough testing.

New changes:
- Handle corner cases of 0 and 1 snapshots
- Disabled button for "Delete Snapshots" when there are no snapshots (except the 0th one).
- Make confirmation button for deleting snapshots red.

**Comment by JosephKiranBabu** [comment]
@jvalleroy Added many refactoring commits. Please squash them.

**Comment by jvalleroy** [comment]
Squashed and merged these changes.

**Pull request closed without merging**
