### PR TITLE
Minor: Fix wrong datetime ConfigurationView import

### PR DESCRIPTION
**Pull request by fonfon**
.. and renamed transmissions ConfigurationView to be more explicit.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
Made minor indentation fix, signed and merged. I suppose the rename is about styling, could not see and argument for one way or the other.

**Comment by fonfon** [comment]
Yes, the renaming was just to make it more explicit that it's not the default plinth ConfigurationView.

**Comment by SunilMohanAdapa** [comment]
On 03/14/2016 08:38 PM, fonfon wrote:
> Yes, the renaming was just to make it more explicit that it's not the
> default plinth ConfigurationView.

It seems to also be similar to how Django is naming things, for example,
the middleware classes.  So, I thought it was okay.

-- 
Sunil

**Comment by fonfon** [comment]
Which part of Django do you mean exactly? On a quick look I only found middleware-classes inheriting from `object` directly, for example
https://github.com/django/django/blob/master/django/contrib/sessions/middleware.py#L11
https://github.com/django/django/blob/master/django/contrib/messages/middleware.py#L5

**Comment by SunilMohanAdapa** [comment]
On 03/14/2016 10:01 PM, fonfon wrote:
> Which part of Django do you mean exactly? On a quick look I only found
> middleware-classes inheriting from |object| directly, for example
> https://github.com/django/django/blob/master/django/contrib/sessions/middleware.py#L11
> https://github.com/django/django/blob/master/django/contrib/messages/middleware.py#L5

It is not about inheritance.  The session middleware class is in
sessions.middleware namespace but they still chose to call it
SessionMiddleware and not just Middleware.  Just like you made the
correction to have the class name TranmissionConfigurationView even
though it is in the namespace transmission.views.  Some more example
which fit the discussion:

            'django.contrib.sessions.middleware.SessionMiddleware',
            'django.middleware.locale.LocaleMiddleware',
            'django.middleware.common.CommonMiddleware',
            'django.middleware.csrf.CsrfViewMiddleware',
            'django.contrib.auth.middleware.AuthenticationMiddleware',

-- 
Sunil

**Comment by fonfon** [comment]
Ah I misunderstood your comment, sorry - initially I thought you meant the original code was closer to the Django naming convention than my changes. All good! :)

**Pull request closed without merging**
