### PR TITLE
openvpn: added line break to label

### PR DESCRIPTION
**Pull request by morrme**
Fixes: https://github.com/freedombox/Plinth/issues/816

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
Merged.  Thank you for the patch and welcome to the project :) If you need help with anything, please feel free to contact us on IRC or mailing list.

**Comment by morrme** [comment]
@SunilMohanAdapa Hi , this says it wasn't merged yet, just closed. Is it safe to get rid of the branch or should I wait?

**Comment by SunilMohanAdapa** [comment]
@morrme , This patch has been merged properly.  You can see it here: https://github.com/freedombox/Plinth/commit/e63197ee2e33eb8a76a97cb148361b255157bbc3

We have practice of signing the commits before merging them.  When signing is done, the commit hash changes and Github does not recognize this as the same commit that was submitted.  So, it shows as closed instead of merged.  I am writing a comment after the merge saying that the merge happened to reduce the confusion.

**Comment by morrme** [comment]
@SunilMohanAdapa Thanks for the explanation!

**Pull request closed without merging**
