### PR TITLE
icons-changed

### PR DESCRIPTION
**Pull request by mridulnagpal**
Changed the icons on frontpage to corresponding app icons 
screenshot from 2016-12-05 02 23 35

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jvalleroy #594

**Comment by mray** [comment]
I think I'd make them even smaller.
At least for the xmpp server I guess the generic XMPP logo isn't appropriate, it is the logo for the protocol itself, not a particular client/server. We use ejabberd, so under its logo it probably should say "XMPP server (ejabberd)"

**Comment by jvalleroy** [comment]
@mridulnagpal I don't think we want to have the user's browser fetching all of these logos from different sites. Rather they should be served by the FreedomBox itself. So we should investigate whether these icons are available in any packages in Debian. If not, we can include them in Plinth but need to track in the LICENSES file.

**Comment by mridulnagpal** [comment]
@jvalleroy @mray On it.

**Comment by mridulnagpal** [comment]
@jvalleroy I downloaded the icons and put them into static/theme/icons
Then I loaded static on the index.html page now when I go for something
like    I don't see an image
on the frontpage please help

**Comment by jvalleroy** [comment]
@mridulnagpal Should that be "{% static 'theme/icons/jsxc.png' %}" ?

**Comment by mridulnagpal** [comment]
@jvalleroy jsxc.png is just an example

**Comment by jvalleroy** [comment]
@mridulnagpal But is it in theme/img or theme/icons?

**Comment by mridulnagpal** [comment]
I put the file in both for testing

**Comment by jvalleroy** [comment]
@mridulnagpal Can you check that the file got installed under /usr/share/plinth/static?

I think the setup.py install (or vagrant provision) won't re-install the files in this folder, if it already exists.

**Comment by mridulnagpal** [comment]
@jvalleroy So how do you suggest I proceed?

**Comment by jvalleroy** [comment]
@mridulnagpal In vagrant you can do this:
```
vagrant@freedombox:/vagrant$ sudo rm -rf /usr/share/plinth/static/
vagrant@freedombox:/vagrant$ sudo ./setup.py test
```
Then any new files under static should be installed.

**Comment by mridulnagpal** [comment]
Actually I have never used SSH to access plinth. How do I do that?

**Comment by jvalleroy** [comment]
@mridulnagpal If you are already using vagrant to run plinth (following https://github.com/freedombox/Plinth/blob/master/HACKING#L3) then you can just run this command:
```
$ vagrant ssh
```
This will SSH into the running vagrant box.

**Pull request closed without merging**
