### PR TITLE
I have made the changes in wiki debian page as well as the README.md file as stated in issue #621

### PR DESCRIPTION
**Pull request by mridulnagpal**

### CODE REVIEW

**Comment by jvalleroy** [comment]
Looking at https://wiki.debian.org/FreedomBox/Plinth, it looks like 2 of the screenshots are missing. Maybe they just need to be renamed?

**Comment by mridulnagpal** [comment]
I checked the readme file all the snapshots are visible in my fork. I put
up 2 new snapshots there. It just takes a little time to load. Right now I
am sending you the screenshots of the readme page in my fork

**Comment by mridulnagpal** [comment]
Now i am on my laptop and rechecked my fork for Plinth and checked that
there are all four images (updated) in the README.md file so I am awaiting
for your reply if there are any changes I should make in my PR. I am
attaching screenshots of my fork of the README.md file. I am also attaching
the screenshot of the wiki debian page.

**Comment by jvalleroy** [comment]
Yes this looks good. I rebased to squash all the commits into 1, and removed a change to Vagrantfile that got added accidentally I think. The change has been merged into our master branch now. Thanks!

**Pull request closed without merging**
