### PR TITLE
Github issue 314: static IP configuration enhancement

### PR DESCRIPTION
**Pull request by steglicd**
* extended Static IP configuration:
  * allow configuration of netmask (optional)
  * allow configuration of Gateway (optional)
  * allow configuartion of two DNS Servers (optional)
* extend DHCP configuration:
  * allow configuration of user specific DNS Server

### CODE REVIEW

**Comment by steglicd** [comment]
This is related to a recent mailing list request:
"Also, i would like to configure my network statically for now.
How can i do that in the "Networks"-Setting? "

- I think this pull request should solve this.

**Comment by SunilMohanAdapa** [comment]
I found that Wi-Fi related changes are not done although the Wi-FI form has new items.  I thought of updating that based on your work with Ethernet so that the patch goes into release but didn't have enough time.  We have decided to make a point release of Plinth in a week.  We can fit this in there.

**Comment by steglicd** [comment]
@SunilMohanAdapa 
I'm sorry - you are right. I have not tested WiFi settings.

I have updated the pull request, WiFi settings are now also complete.

**Comment by SunilMohanAdapa** [comment]
I have merged this after a rebase and following fixes. Please review my changes.

- I18N for help labels.
- Minor indentation.
- Fix byte order when extracting netmask (should be same as for IP address, that is, host byte order)
- Fix setting default netmask when netmask is not provided

I also got into refactoring some of the networking code while doing this.  I will raise a pull request for that separately.

**Pull request closed without merging**
